from django_auth_lti.const import (ADMINISTRATOR, CONTENT_DEVELOPER,
    TEACHING_ASSISTANT, INSTRUCTOR)


ADMINS = [ADMINISTRATOR, CONTENT_DEVELOPER, TEACHING_ASSISTANT, INSTRUCTOR]
STAGE_URL_TAG = 'intervention_point_url_'
DEPLOY_OPTION_TAG = 'is_canvas_page_for_track_'

NAME_CHAR_LIMIT = 256
URL_CHAR_LIMIT = 2048
NOTES_CHAR_LIMIT = 1024

